language: go

go:
  - 1.2
  - 1.3
  - 1.4

script: $TRAVIS_BUILD_DIR/test.sh

branches:
  only: master

notifications:
  irc:
    channels:
      - "irc.freenode.net#cgrates"
    on_success: change
    on_failure: always
  email:
    on_success: never
    on_failure: always

